# created by M. van Beekveld
# mcbeekveld@gmail.com
# simple file to convert slha file generated by suspect, spheno etc. to madgraph input
##########
# set your MG5 dir here, since it needs the converter in Madgraph. 
import sys
sys.path.append('/scratch/mbeekveld/MG5_aMC_v2_6_3_2')
import models.check_param_card as converter

# set slhafile to generated file
# outputfile is name_original_file(.dat)_converted.dat
slhafile = "input_slha.dat"
slhafile = "/scratch/mbeekveld/MG5_aMC_v2_6_3_2/bin/simplified_gluino1400_neu1.dat"
output_path = slhafile.replace(".dat","")+"_AAAconverted.dat"

converter.convert_to_mg5card(slhafile, output_path)
print "Converted file is "+output_path
